name: Continuous integration

on: 
  pull_request:
    paths:
      - "**.wdl"  # Workflow files and task 
      - "**.yml"  # Ci configuration, tests and docker images 
      - "!docs/**"

defaults:
  run:
    # This is needed for miniconda, see:
    # https://github.com/marketplace/actions/setup-miniconda#important
    shell: bash -l {0}  

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Womtool validate and submodule up to date.
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          submodules: recursive
      - name: install miniconda
        uses: conda-incubator/setup-miniconda@v2.0.1
        with:
          channels: conda-forge,bioconda,defaults
        # Conda-incubator uses 'test' environment by default.
      - name: install requirements
        run: conda install -n test cromwell miniwdl wdl-aid
      - name: run linting
        run: bash scripts/biowdl_lint.sh